# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureKeyVault@1
  displayName: Azure Key Vault $(ProjectName)
  inputs:
    azureSubscription: 'Visual Studio Enterprise (e945f6ed-8c00-4129-8ecd-263ec98eaf36)'
    KeyVaultName: 'key-vault-masterchech'
    SecretsFilter: '*'
    RunAsPreJob: true

- task: PowerShell@2
  displayName: Build Net Api $(ProjectName) $(Version)
  inputs:
    filePath: './BuildNetApi.ps1'
    arguments: './BuildNetApi.ps1; CIBuildNetApi'
  timeoutInMinutes: 10
  continueOnError: false
  
- task: PublishTestResults@2
  displayName: Publish Test Result Net Api $(ProjectName) $(Version)
  inputs:
    testResultsFormat: VSTest
    testResultsFiles: '**/*.trx'
    failTaskOnFailedTests: true

- task: PublishCodeCoverageResults@1
  displayName: Publish Code Coverage Net Api $(ProjectName) $(Version)
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/build/test/coverage/coverage.cobertura.xml'
    failIfCoverageEmpty: true

- task: Docker@2
  displayName: Build and Push Docker Image Net Api $(ProjectName) $(Version)
  inputs:
    containerRegistry: 'Container Registry MasterChech'
    repository: 'master-chech-webapi'
    command: 'buildAndPush'
    Dockerfile: '$(System.DefaultWorkingDirectory)/src/api/MasterChechBotWebApi/Dockerfile'
    buildContext: '$(System.DefaultWorkingDirectory)/src/api/MasterChechBotWebApi/'
    tags: |
      $(Build.BuildId)
      latest

- task: PowerShell@2
  displayName: Build React WebApp $(ProjectName) $(Version)
  inputs:
    filePath: './BuildReactApp.ps1'
    arguments: './BuildReactApp.ps1;  $env:URLAPI="http://master-chech-webapi.brazilsouth.azurecontainer.io"; $env:APIKEYHEADER="$(API-KEY-HEADER)"; CIBuildReact;'
  timeoutInMinutes: 10
  continueOnError: false

- task: Docker@2
  displayName: Build Docker Image React WebApp $(ProjectName) $(Version)
  inputs:
    containerRegistry: 'Container Registry MasterChech'
    repository: 'master-chech-webapp'
    command: build
    Dockerfile: '$(System.DefaultWorkingDirectory)/src/webapp/Dockerfile'
    buildContext: '$(System.DefaultWorkingDirectory)/src/webapp/'    
    tags:  |
      $(Build.BuildId)
      latest

- task: Docker@2
  displayName: Push Docker Image React WebApp $(ProjectName) $(Version)
  inputs:
    containerRegistry: 'Container Registry MasterChech'
    repository: 'master-chech-webapp'  
    command: push
    tags:  |
      $(Build.BuildId)
      latest

- task: PublishBuildArtifacts@1
  displayName: Publish Powershell Deploy Azure $(ProjectName) $(Version)
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/DeployAzureContainer.ps1'
    ArtifactName: 'script-powershell-for-deploy'
    publishLocation: 'Container'      