# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  
steps:
- task: PowerShell@2
  displayName: Build Net Api $(ProjectName) $(Version)
  inputs:
    filePath: './BuildNetApi.ps1'
    arguments: './BuildNetApi.ps1; PrivateBuildNetApi'
  timeoutInMinutes: 10

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'XUnit'
    testResultsFiles: '**/*.trx'
    searchFolder: '$(System.DefaultWorkingDirectory)/build/test'
    failTaskOnFailedTests: true

- task: PowerShell@2
  displayName: Build React WebApp $(ProjectName) $(Version)
  inputs:
    filePath: './BuildReactApp.ps1'
    arguments: './BuildReactApp.ps1;  PrivateBuildReact'
  timeoutInMinutes: 10
