version: '3.4'

services:
  master.chech.bot.webapi:
    image: master-chech-bot-webapi
    build:
      context: ./src/api/src/MasterChechBot.WebApi/
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      TZ: America/Sao_Paulo
      BotKey: "BotKey"
      ApiKeyValid: "ApiKeyValid"
      ConnectionString: "ConnectionString"
  master.chech.bot.webapp:
    image: master-chech-bot-webapp
    build:
      context: ./src/webapp/
      dockerfile: Dockerfile
    ports:
      - "5002:80"